const mongoose = require("mongoose");
const validator = require("mongoose-unique-validator");
const vehicleInspectionSchema = new mongoose.Schema({
  date: { type: String },
  employee: { type: String },
  vehicle: { type: String },
  mileage: { type: String },
  headLights: { type: Boolean },
  tailLights: { type: Boolean },
  turnSignals: { type: Boolean },
  brakeLights: { type: Boolean },
  reflectors: { type: Boolean },
  tiresRims: { type: Boolean },
  battery: { type: Boolean },
  radiator: { type: Boolean },
  exhaustSystem: { type: Boolean },
  suspension: { type: Boolean },
  fuelSystem: { type: Boolean },
  leaks: { type: Boolean },
  waterLevel: { type: Boolean },
  tranmission: { type: Boolean },
  gauges: { type: Boolean },
  horn: { type: Boolean },
  windShield: { type: Boolean },
  windshieldWipers: { type: Boolean },
  speedometer: { type: Boolean },
  steering: { type: Boolean },
  brakeSystem: { type: Boolean },
  seatBelts: { type: Boolean },
  seats: { type: Boolean },
  heater: { type: Boolean },
  mirrors: { type: Boolean },
  safetyEquipment: { type: Boolean },
  accidentKit: { type: Boolean },
  other: { type: Boolean },
  damage: { type: String },
  remarks: { type: String },
  signedBy: { type: String },
});
module.exports = mongoose.model("vehicleInspections", vehicleInspectionSchema);
